### PR TITLE
fixes #113 using fetch + keepalive

### LINKED ISSUE #113: use fetch + keepalive
bumped into https://css-tricks.com/send-an-http-request-on-page-exit/ which describes a more reliable way to make sure requests are sent, even when the user leaves the page, using `fetch` + `keepalive`. Not sure if [older browsers support it](https://caniuse.com/fetch), or if we can use a shim. Another option is to replace the [jQuery get](https://github.com/Alephbet/alephbet/blob/1193a210cdf670e5b4dd926542cfc38c70b0c985/src/adapters/alephbet_adapter.js#L29) with a `fetch` if it's available, or fallback on the [plain JS get](https://github.com/Alephbet/alephbet/blob/1193a210cdf670e5b4dd926542cfc38c70b0c985/src/adapters/alephbet_adapter.js#L39).

### PR DESCRIPTION
**Pull request by gingerlime**
* instead of jQuery, we check if the browser supports `fetch`
  and use it with `keepalive: true`
* otherwise, fallback to plain JS

### CODE REVIEW

**Comment by gingerlime** [comment]
@joker-777 can you take a look? :)

**Review by joker-777 — APPROVED** [review]
@gingerlime Sorry, I had a look at it already yesterday but then forgot to write a comment. The code changes look very good. How can I test it best?

**Comment by gingerlime** [comment]
@joker-777 thank you. We have some tests, but they are far from perfect. I tested manually with an HTML page that loaded a simple experiment, and I saw that it was using `fetch` to send the results. I'm not sure what else we can do here.

**Comment by joker-777** [comment]
@gingerlime Sounds good to me.

**Pull request merged**
