### PR TITLE
doc: briefly explain weights in intro example

### PR DESCRIPTION
**Pull request by zwacky**
rather than skimming through the PR. great addition btw 👍

### CODE REVIEW

**Comment by gingerlime** [comment]
Thanks for the contribution @zwacky !

The code snippet belongs to the quick start section of the readme, and I therefore deliberately kept it simple. If someone’s looking for more options and features, these are listed further down.

I’m not opposed to making the docs around the weight options better, but would prefer to keep the intro as simple as possible.

**Comment by zwacky** [comment]
I understand. then at least have a snippet under the 'weights' section?

**Comment by zwacky** [comment]
alright lemme add that then

**Comment by zwacky** [comment]
there ya go

**Pull request merged**
