### PR TITLE
Uses instance properties instead of static properties for the adapters

### PR DESCRIPTION
**Pull request by joker-777**

### CODE REVIEW

**Review by gingerlime — APPROVED** [review]
👍 thank you!

**Comment by gingerlime** [comment]
The tests are failing though?

**Comment by joker-777** [comment]
Ah, yes, I forgot to run `yarn run build`.

**Comment by gingerlime** [comment]
@joker-777 thank you. I also noticed that the changelog wasn't updated. Could you update it with the latest changes you merged?

**Comment by joker-777** [comment]
Don't you think it makes sense to use the [releases](https://github.com/Alephbet/alephbet/releases) to document this?

**Comment by gingerlime** [comment]
If it's possible to retrofit all the changes into the (old) releases, then I guess that's an option.

Otherwise, I think it's nice to have a clear changelog, and that's what I was doing from the beginning.

**Comment by joker-777** [comment]
It looks like you can update the description of existing releases. Should I do this?

**Comment by gingerlime** [comment]
If you could, then sounds like a great idea. Thank you!

If we can then copy over all the CHANGELOG entries to the releases, then we can remove the file and keep everything in one place 👍

**Pull request merged**
